use std::collections::{HashMap, HashSet};

use crate::{Event, EventId, Operation, TaskId};

/// Returns the `TaskId` referenced by any `Operation` variant.
fn task_id_of(operation: &Operation) -> TaskId {
    match operation {
        Operation::Create(task_id) => *task_id,
        Operation::Claim(task_id, _) => *task_id,
        Operation::Complete(task_id, _) => *task_id,
    }
}

/// Append-only directed acyclic graph of causal events.
///
/// This is the core CRDT data structure. Events are stored by `EventId` and
/// causal edges are recorded in a separate `children` map so that edges for
/// not-yet-received parents can be stored without blocking insertion.
///
/// Fields are private: mutation only ever happens through [`Self::insert`],
/// [`Self::merge`], and [`Self::record_edge`], so the `children` map can't be
/// pushed out of sync with the events it indexes by a caller poking the
/// field directly. Read access goes through [`Self::events`], [`Self::children`],
/// and the narrower per-id/per-task accessors below.
#[derive(Clone, Debug, Default)]
pub struct CausalGraph {
    events: HashMap<EventId, Event>,
    children: HashMap<EventId, HashSet<EventId>>,
    /// Index from `TaskId` to the ids of events whose operation references it,
    /// maintained incrementally on `insert` so task-scoped lookups (used by
    /// `task_model::extract_task_subgraph`) don't have to scan every event.
    by_task: HashMap<TaskId, HashSet<EventId>>,
}

impl CausalGraph {
    /// Creates an empty `CausalGraph`.
    pub fn new() -> Self {
        Self::default()
    }

    /// All known events, indexed by their unique `EventId`.
    pub fn events(&self) -> &HashMap<EventId, Event> {
        &self.events
    }

    /// The number of known events.
    pub fn event_count(&self) -> usize {
        self.events.len()
    }

    /// `true` if an event with this id has been inserted.
    pub fn contains_event(&self, event_id: &EventId) -> bool {
        self.events.contains_key(event_id)
    }

    /// The full parent-to-children edge map.
    pub fn children(&self) -> &HashMap<EventId, HashSet<EventId>> {
        &self.children
    }

    /// The ids of events that list `parent` in their `causal_parents`, if any.
    pub fn children_of(&self, parent: &EventId) -> Option<&HashSet<EventId>> {
        self.children.get(parent)
    }

    /// All events whose operation references `task_id`, via the `by_task` index.
    pub fn events_for_task(&self, task_id: &TaskId) -> impl Iterator<Item = &Event> {
        self.by_task
            .get(task_id)
            .into_iter()
            .flatten()
            .filter_map(|id| self.events.get(id))
    }

    /// Records that `child` lists `parent` in its `causal_parents`, without
    /// requiring `parent`'s event to be known yet.
    ///
    /// `insert` calls this for every event it accepts; it's also exposed so
    /// callers building a derived graph (e.g. task_model's subgraph
    /// extraction) can carry over edges without reaching into private state.
    pub fn record_edge(&mut self, parent: EventId, child: EventId) {
        self.children.entry(parent).or_default().insert(child);
    }

    /// Inserts an event into the graph.
    ///
    /// If an event with the same `event_id` already exists the call is a no-op.
    /// Causal edges are recorded for all entries in `causal_parents` even if
    /// those parent events have not yet been inserted.
    ///
    /// `causal_parents` is trusted as given: nothing here checks that a
    /// referenced parent ever actually arrives, or that the graph stays
    /// acyclic. That's fine for this closed simulation, where every event is
    /// generated by [`crate::message::Message`]-carrying nodes that only ever
    /// cite real, already-issued ids — it would not be safe to assume for
    /// events accepted from an untrusted network peer, which could cite a
    /// fabricated or cyclic parent to influence causal ordering.
    pub fn insert(&mut self, event: Event) {
        if self.events.contains_key(&event.event_id) {
            return;
        }

        for parent_id in &event.causal_parents {
            self.record_edge(*parent_id, event.event_id);
        }

        self.by_task
            .entry(task_id_of(&event.operation))
            .or_default()
            .insert(event.event_id);

        self.events.insert(event.event_id, event);
    }

    /// Merges another `CausalGraph` into this one.
    ///
    /// The operation is idempotent, commutative, and associative (CRDT join).
    /// Reusing `insert` for events guarantees the duplicate-skip, edge-recording,
    /// and `by_task`-indexing logic stays in one place. The children union handles
    /// edges that `other` recorded for parents that were absent at insertion time —
    /// those edges may not be re-derived from the events alone, so we must merge
    /// the edge sets directly.
    pub fn merge(&mut self, other: &CausalGraph) {
        for event in other.events.values() {
            self.insert(event.clone());
        }

        for (parent_id, child_set) in &other.children {
            self.children
                .entry(*parent_id)
                .or_default()
                .extend(child_set.iter().cloned());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{NodeId, Operation, TaskId};

    fn create_event(id: u128, op: Operation, parents: Vec<u128>) -> Event {
        Event {
            event_id: EventId(id),
            operation: op,
            causal_parents: parents.into_iter().map(EventId).collect(),
        }
    }

    #[test]
    fn new_graph_is_empty() {
        let graph = CausalGraph::new();
        assert!(graph.events.is_empty());
        assert!(graph.children.is_empty());
    }

    #[test]
    fn events_for_task_returns_only_matching_task() {
        let mut graph = CausalGraph::new();
        graph.insert(create_event(1, Operation::Create(TaskId(10)), vec![]));
        graph.insert(create_event(
            2,
            Operation::Claim(TaskId(10), NodeId(1)),
            vec![1],
        ));
        graph.insert(create_event(3, Operation::Create(TaskId(20)), vec![]));

        let ids: HashSet<EventId> = graph
            .events_for_task(&TaskId(10))
            .map(|e| e.event_id)
            .collect();

        assert_eq!(ids, HashSet::from([EventId(1), EventId(2)]));
    }

    #[test]
    fn events_for_task_empty_for_unknown_task() {
        let mut graph = CausalGraph::new();
        graph.insert(create_event(1, Operation::Create(TaskId(10)), vec![]));

        assert_eq!(graph.events_for_task(&TaskId(99)).count(), 0);
    }

    #[test]
    fn record_edge_works_before_parent_event_arrives() {
        let mut graph = CausalGraph::new();
        graph.record_edge(EventId(1), EventId(2));

        assert!(
            graph
                .children_of(&EventId(1))
                .unwrap()
                .contains(&EventId(2))
        );
        assert!(!graph.contains_event(&EventId(1)));
    }

    #[test]
    fn insert_single_event_no_parents() {
        let mut graph = CausalGraph::new();
        graph.insert(create_event(1, Operation::Create(TaskId(10)), vec![]));

        assert_eq!(graph.events.len(), 1);
        assert!(graph.children.is_empty());
    }

    #[test]
    fn insert_child_with_existing_parent() {
        let mut graph = CausalGraph::new();
        graph.insert(create_event(1, Operation::Create(TaskId(10)), vec![]));
        graph.insert(create_event(
            2,
            Operation::Claim(TaskId(10), NodeId(20)),
            vec![1],
        ));

        assert_eq!(graph.events.len(), 2);
        assert!(graph.children[&EventId(1)].contains(&EventId(2)));
    }

    #[test]
    fn insert_child_before_parent_arrives() {
        let mut graph = CausalGraph::new();
        graph.insert(create_event(
            2,
            Operation::Claim(TaskId(10), NodeId(20)),
            vec![1],
        ));

        assert_eq!(graph.events.len(), 1);
        assert!(graph.children[&EventId(1)].contains(&EventId(2)));
    }

    #[test]
    fn duplicate_insert_is_ignored() {
        let mut graph = CausalGraph::new();
        graph.insert(create_event(1, Operation::Create(TaskId(10)), vec![]));
        graph.insert(create_event(1, Operation::Create(TaskId(10)), vec![]));

        assert_eq!(graph.events.len(), 1);
    }

    #[test]
    fn merge_two_disjoint_graphs() {
        let mut a = CausalGraph::new();
        a.insert(create_event(1, Operation::Create(TaskId(1)), vec![]));

        let mut b = CausalGraph::new();
        b.insert(create_event(2, Operation::Create(TaskId(2)), vec![]));

        a.merge(&b);

        assert_eq!(a.events.len(), 2);
        assert!(a.events.contains_key(&EventId(1)));
        assert!(a.events.contains_key(&EventId(2)));
    }

    #[test]
    fn merge_overlapping_graphs() {
        let mut a = CausalGraph::new();
        a.insert(create_event(1, Operation::Create(TaskId(1)), vec![]));
        a.insert(create_event(
            2,
            Operation::Claim(TaskId(1), NodeId(1)),
            vec![1],
        ));

        let mut b = CausalGraph::new();
        b.insert(create_event(1, Operation::Create(TaskId(1)), vec![]));
        b.insert(create_event(
            3,
            Operation::Complete(TaskId(1), NodeId(1)),
            vec![1],
        ));

        a.merge(&b);

        assert_eq!(a.events.len(), 3);
    }

    #[test]
    fn merge_empty_into_non_empty() {
        let mut a = CausalGraph::new();
        a.insert(create_event(1, Operation::Create(TaskId(1)), vec![]));

        let empty = CausalGraph::new();
        a.merge(&empty);

        assert_eq!(a.events.len(), 1);
        assert!(a.children.is_empty());
    }

    #[test]
    fn merge_non_empty_into_empty() {
        let mut empty = CausalGraph::new();

        let mut source = CausalGraph::new();
        source.insert(create_event(1, Operation::Create(TaskId(1)), vec![]));
        source.insert(create_event(
            2,
            Operation::Claim(TaskId(1), NodeId(1)),
            vec![1],
        ));

        empty.merge(&source);

        assert_eq!(empty.events.len(), 2);
        assert!(empty.children[&EventId(1)].contains(&EventId(2)));
    }
}
